export const CLEAR_CREDENTIALS = 'CLEAR_CREDENTIALS';
export const CHECK_CREDENTIALS = 'CHECK_CREDENTIALS';
export const CHECK_CREDENTIALS_SUCCESS = 'CHECK_CREDENTIALS_SUCCESS';
export const CHECK_CREDENTIALS_FAILURE = 'CHECK_CREDENTIALS_FAILURE';
export const ADD_CREDENTIALS = 'ADD_CREDENTIALS';
export const ADD_CREDENTIALS_SUCCESS = 'ADD_CREDENTIALS_SUCCESS';
export const ADD_CREDENTIALS_FAILURE = 'ADD_CREDENTIALS_FAILURE';
